[package]
name = "tube-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
regex.workspace = true
serde.workspace = true
serde_json.workspace = true
reqwest.workspace = true
tokio.workspace = true
serde-xml-rs = "0.6"
dotenv.workspace = true


# [dev-dependencies]
